* Added TODO * Fixed false error messages

diff --git a/ytpl-sync b/ytpl-sync
--- a/ytpl-sync
+++ b/ytpl-sync
@@ -1,4 +1,7 @@
 #!/bin/sh
+# TODO
+# - Replace "reserved characters" with alternatives for file names:
+#   https://stackoverflow.com/questions/10386344/how-to-get-a-file-in-windows-with-a-colon-in-the-filename#25477235
 
 y_or_n="[\033[1;32my\033[0m/\033[31mN\033[0m]"
 msg_help="
@@ -189,7 +192,7 @@ if ! [ "${pl_url}" ]; then
 	printf 'Playlist URL: '
 	read pl_url
 	[ "${pl_url}" ] || error "URL not provided"
-	check_url "${pl_url}" || error "Invalid URL: ${2}"
+	check_url "${pl_url}" || error "Invalid URL: ${pl_url}"
 fi
 
 if ! [ "${pl_dir}" ]; then
@@ -202,7 +205,7 @@ if ! [ "${pl_dir}" ]; then
 			error "Directory '~/Music/' doesn't exist"
 		fi
 	else
-		check_dir "${pl_dir}" || error "Invalid url: ${2}"
+		check_dir "${pl_dir}" || error "Directory doesn't exist: ${pl_dir}"
 	fi
 fi
 
