Better text formatting

diff --git a/ytpl-sync b/ytpl-sync
--- a/ytpl-sync
+++ b/ytpl-sync
@@ -54,28 +54,17 @@ get_info() {
 				# Replace forbidden filename characters
 				title=$(
 					printf '%s\n' "${title}" |
-						sed -e 's/\\\\/⑊/g' \
-							-e 's/"/”/g' \
-							-e 's|/|∕|g' \
-							-e 's/:/꞉/g' \
-							-e 's/</‹/g' \
-							-e 's/>/›/g' \
-							-e 's/?/︖/g' \
-							-e 's/\\/＼/g' \
-							-e 's/|/⏐/g' \
+						sed -e 's/"/”/g' \
+					        -e 's|/|╱|g' \
+					        -e 's/:/꞉/g' \
+					        -e 's/</‹/g' \
+					        -e 's/>/›/g' \
+					        -e 's/?/︖/g' \
+					        -e 's/\\/╲/g' \
+					        -e 's/|/│/g' \
                             -e "s/^[.]*//" \
                             -e 's/^ *//'
 					 )
-				# title=$(replace "\\\\" "⑊" "${title}")
-				# title=$(replace '"' "”" "${title}")
-				# title=$(replace "*" "⁎" "${title}")
-				# title=$(replace "/" "∕" "${title}")
-				# title=$(replace ":" "꞉" "${title}")
-				# title=$(replace "<" "‹" "${title}")
-				# title=$(replace ">" "›" "${title}")
-				# title=$(replace "?" "︖" "${title}")
-				# title=$(replace "\\" "＼" "${title}")
-				# title=$(replace "|" "⏐" "${title}")
 				tmp="${tmp}${title} ${id}${newline}"
 			done
 			printf '%s\n\n' "${tmp}"
@@ -93,14 +82,6 @@ check_url() {
 check_dir() {
 	[ -d "${1}" ] || return 1
 	return 0
-}
-
-# Checks whether ${1} is a supported format
-check_format() {
-	for format in "mp4" "webm" "aac" "flac" "mp3" "m4a" "opus" "vorbis"; do
-		[ "${1}" = "${format}" ] && return 0
-	done
-	return 1
 }
 
 # Sets ${1} as ${pl_format} or return 1 if it's not a supported format
@@ -127,11 +108,16 @@ sync_download() {
 	for line in ${1}; do
 		title=${line% *}
 		url="https://www.youtube.com/watch?v=${line##* }"
-		if ! [ -f "${pl_dir%/}/${title}.mp3" ]; then
+		if ! [ -f "${pl_dir%/}/${title}.${pl_format}" ]; then
 			ran=true
+            printf "\033[1;34mDownloading\033[m %s.%s\n" \
+                   "${title}" \
+                   "${pl_format}"
 			if [ "${pl_type}" = "audio" ]; then
 		   		${bin} "${url}" \
-					   -x \
+                       -q \
+                       --progress \
+				       -x \
 		 			   --audio-format "${pl_format}" \
 		 			   --add-metadata --metadata-from-title "%(title)s" \
 		 			   --postprocessor-args \
@@ -139,10 +125,21 @@ sync_download() {
 		 			   -o "${pl_dir}/${title}.%(ext)s"
 			else
 				${bin} "${url}" \
-					   --add-metadata --metadata-from-title "$(title)s" \
+                       -q \
+                       --progress \
+				       --add-metadata --metadata-from-title "$(title)s" \
 					   -o "${pl_dir}/${title}.%(ext)s"
 			fi
-		fi
+            if [ $? -ne 0 ]; then # If ytdl fails
+                printf "\033[1;31mFailed\033[m to download %s\n" \
+                       "${title}.${pl_format}"
+                exit 1
+            fi
+        else
+            printf "\033[1;33mSkipping\033[m %s.%s, already exists\n" \
+                   "${title}" \
+                   "${pl_format}"
+        fi
 	done
 	${ran} || notice 'No media needed to be downloaded'
 }
@@ -157,7 +154,8 @@ sync_remove() {
 			[ "${line% *}.${pl_format}" = "${file}" ] && continue 2
 		done
 		ran=true
-		rm -v "${pl_dir%/}/${file}"
+        printf "\033[1;31mRemoving\033[m %s\n" "${file}"
+		rm "${pl_dir%/}/${file}"
 	done
 	${ran} || notice 'No media needed to be removed'
 }
